<?php

/**
 * @file
 * Contains agid_fixtures.install.
 */

/**
 * Implements hook_uninstall().
 */
function agid_fixtures_uninstall() {

  $configs = [
    'migrate_plus.migration.agid_fixtures_basic_custom_block.yml',
    'migrate_plus.migration.agid_fixtures_ct_acc_subj_from_ente.yml',
    'migrate_plus.migration.agid_fixtures_ct_acc_subj_from_spid.yml',
    'migrate_plus.migration.agid_fixtures_ct_event.yml',
    'migrate_plus.migration.agid_fixtures_ct_faq.yml',
    'migrate_plus.migration.agid_fixtures_ct_news.yml',
    'migrate_plus.migration.agid_fixtures_ct_page_page.yml',
    'migrate_plus.migration.agid_fixtures_ct_page_pagina_generica_alberatura.yml',
    'migrate_plus.migration.agid_fixtures_ct_page_subhomepage.yml',
    'migrate_plus.migration.agid_fixtures_ct_person.yml',
    'migrate_plus.migration.agid_fixtures_ct_press.yml',
    'migrate_plus.migration.agid_fixtures_ct_software.yml',
    'migrate_plus.migration.agid_fixtures_empty_page_footer_middle.yml',
    'migrate_plus.migration.agid_fixtures_empty_page_main_menu.yml',
    'migrate_plus.migration.agid_fixtures_empty_page.yml',
    'migrate_plus.migration.agid_fixtures_entity_browser.yml',
    'migrate_plus.migration.agid_fixtures_files.yml',
    'migrate_plus.migration.agid_fixtures_home_page_highlight_queue.yml',
    'migrate_plus.migration.agid_fixtures_images.yml',
    'migrate_plus.migration.agid_fixtures_menu_faq.yml',
    'migrate_plus.migration.agid_fixtures_menu_footer_bottom.yml',
    'migrate_plus.migration.agid_fixtures_menu_footer_middle.yml',
    'migrate_plus.migration.agid_fixtures_menu_links.yml',
    'migrate_plus.migration.agid_fixtures_menu_siti_tematici.yml',
    'migrate_plus.migration.agid_fixtures_organizational_chart_queue.yml',
    'migrate_plus.migration.agid_fixtures_pagina.yml',
    'migrate_plus.migration.agid_fixtures_paragraph_external_link_ente_manual.yml',
    'migrate_plus.migration.agid_fixtures_paragraph_external_link_spid_details.yml',
    'migrate_plus.migration.agid_fixtures_paragraph_external_link_spid_doc.yml',
    'migrate_plus.migration.agid_fixtures_paragraph_external_link_spid_info.yml',
    'migrate_plus.migration.agid_fixtures_paragraph_external_link_spid_meta.yml',
    'migrate_plus.migration.agid_fixtures_paragraph_external_link_spid_reg.yml',
    'migrate_plus.migration.agid_fixtures_paragraph_image.yml',
    'migrate_plus.migration.agid_fixtures_paragraph_more_info_ente_head.yml',
    'migrate_plus.migration.agid_fixtures_paragraph_more_info_ente_substitut.yml',
    'migrate_plus.migration.agid_fixtures_paragraph_more_info_ente_x500.yml',
    'migrate_plus.migration.agid_fixtures_paragraph_more_info_spid_auth.yml',
    'migrate_plus.migration.agid_fixtures_paragraph_more_info_spid_code.yml',
    'migrate_plus.migration.agid_fixtures_paragraph_more_info_spid_sec_level.yml',
    'migrate_plus.migration.agid_fixtures_paragraph_position.yml',
    'migrate_plus.migration.agid_fixtures_paragraph_titletext.yml',
    'migrate_plus.migration.agid_fixtures_taxonomy_acc_subj_type.yml',
    'migrate_plus.migration.agid_fixtures_taxonomy_cad.yml',
    'migrate_plus.migration.agid_fixtures_taxonomy_contact_form.yml',
    'migrate_plus.migration.agid_fixtures_taxonomy_file_category.yml',
    'migrate_plus.migration.agid_fixtures_taxonomy_file_type.yml',
    'migrate_plus.migration.agid_fixtures_taxonomy_news_type.yml',
    'migrate_plus.migration.agid_fixtures_taxonomy_offices.yml',
    'migrate_plus.migration.agid_fixtures_taxonomy_original_file_source.yml',
    'migrate_plus.migration.agid_fixtures_taxonomy_pagopa_type.yml',
    'migrate_plus.migration.agid_fixtures_taxonomy_profiles.yml',
    'migrate_plus.migration.agid_fixtures_taxonomy_roles.yml',
    'migrate_plus.migration.agid_fixtures_taxonomy_tags.yml',
    'migrate_plus.migration.agid_fixtures_users.yml',
    'migrate_plus.migration_group.agid_fixtures_group_contents.yml',
    'migrate_plus.migration_group.agid_fixtures_group_ente_paragraphs.yml',
    'migrate_plus.migration_group.agid_fixtures_group_files.yml',
    'migrate_plus.migration_group.agid_fixtures_group_new_contents.yml',
    'migrate_plus.migration_group.agid_fixtures_group_spid_paragraphs.yml',
    'migrate_plus.migration_group.agid_fixtures_group_taxonomies_db.yml',
    'migrate_plus.migration_group.agid_fixtures_group_taxonomies.yml'
  ];

  foreach ($configs as $config) {

    Drupal::configFactory()->getEditable($config)->delete();

  }
  drupal_flush_all_caches();
}
